name: Robot Automation Suite

on:
  push:
    branches: [ main ]
  pull_request:

env:
  PLAYWRIGHT_HEADLESS: "true"

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        suite: [ plaid, ui ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.suite }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.suite }}-

      - name: Build robot runner image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/robot-runner.Dockerfile
          load: true
          tags: robot-runner:ci
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Run ${{ matrix.suite }} tests
        env:
          PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
          PLAID_SECRET: ${{ secrets.PLAID_SECRET }}
          PLAID_WEBHOOK_URL: ${{ secrets.PLAID_WEBHOOK_URL }}
          PABOT_PROCESSES: 4
        run: |
          if [ "${{ matrix.suite }}" = "plaid" ]; then
            docker run --rm \
              -e PLAID_CLIENT_ID \
              -e PLAID_SECRET \
              -e PLAID_WEBHOOK_URL \
              -e PLAYWRIGHT_HEADLESS \
              -e PABOT_PROCESSES \
              -v "${{ github.workspace }}:/opt/project" \
              robot-runner:ci \
              bash ci/scripts/run-plaid.sh;
          else
            docker run --rm \
              -e PLAYWRIGHT_HEADLESS \
              -e PABOT_PROCESSES \
              -v "${{ github.workspace }}:/opt/project" \
              robot-runner:ci \
              bash ci/scripts/run-ui.sh;
          fi

      - name: Upload Robot reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ matrix.suite }}
          path: |
            reports/**/*
            output.xml
            log.html
            report.html
          if-no-files-found: ignore
